apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deployment-web
  name: deployment-web-svc
  namespace: ravi-prac
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: deployment-web
  type: ClusterIP
status:
  loadBalancer: {}
