apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deployment-web
  name: deployment-web-np-svc
  namespace: ravi-prac
spec:
  ports:
  - port: 8765
    protocol: TCP
    targetPort: 8080
    nodePort: 30678
  selector:
    app: deployment-web
  type: NodePort
status:
  loadBalancer: {}
