apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: b95ef6994f727cb5ea218dc4434c128d9bd93e93135e3602e697b12bebb3ceb7
    cni.projectcalico.org/podIP: 192.168.59.115/32
    cni.projectcalico.org/podIPs: 192.168.59.115/32
  creationTimestamp: "2023-01-05T23:42:26Z"
  generateName: deployment-web-6874fd9887-
  labels:
    app: deployment-web
    pod-template-hash: 6874fd9887
  name: deployment-web-6874fd9887-kdf9k
  namespace: ravi-prac
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: deployment-web-6874fd9887
    uid: ce858900-92fd-4680-a756-e62d76f471ee
  resourceVersion: "1315028"
  uid: 7d8f44c2-413b-463c-9d14-6209dd9e7466
spec:
  containers:
  - image: gcr.io/kodekloud/customimage/my-kubernetes-dashboard
    imagePullPolicy: Always
    name: my-kubernetes-dashboard
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-v99nw
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: centos8-slave
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: dashboard-sa
  serviceAccountName: dashboard-sa
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - hostPath:
      path: /tmp/getpodFile
      type: DirectoryOrCreate
    name: test-volume
  - name: kube-api-access-v99nw
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-01-05T14:30:49Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-01-05T14:30:53Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-01-05T14:30:53Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-01-05T23:42:26Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://c3fd52dbb006949707c9d88e4f258fa36026c34b346bddf831113ba3354730d4
    image: gcr.io/kodekloud/customimage/my-kubernetes-dashboard:latest
    imageID: gcr.io/kodekloud/customimage/my-kubernetes-dashboard@sha256:7d70abe342b13ff1c4242dc83271ad73e4eedb04e2be0dd30ae7ac8852193069
    lastState: {}
    name: my-kubernetes-dashboard
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-01-05T14:30:53Z"
  hostIP: 192.168.56.102
  phase: Running
  podIP: 192.168.59.115
  podIPs:
  - ip: 192.168.59.115
  qosClass: BestEffort
  startTime: "2023-01-05T14:30:49Z"
