apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    type: pvc-with-gc
  name: pvc-with-gc
spec:
  storageClassName: fast-storage-dynamic
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
