apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis
    command: ['/bin/sh', '-c']
    args:
      - |
        for i in {1..100}
        do  
          shuf -i  0-100 -n1 >> /opt/number.out
          echo "Random number is:"
          tail -1 /opt/number.out
          sleep 1
        done

    volumeMounts:
    - name: redis-storage
      mountPath: /opt/
  volumes:
  - name: redis-storage
    hostPath: 
      path: /tmp/AlpinePodData
      type: DirectoryOrCreate
