apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-pod-2
  name: nginx-pod-2
  namespace: ravi-cm
spec:
  containers:
  - image: nginx:alpine
    name: nginx-pod-2
    envFrom:
    - configMapRef:
          name: anotherone
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
