apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sc-demo-pod
  name: sc-demo-pod
  namespace: ravi-cm
spec:
  securityContext:
    runAsUser: 101
    runAsGroup: 3000
    fsGroup: 2000
  containers:
  - image: busybox:alpine
    name: sc-demo-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
