apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: front-end
  name: canay-dep-svc
  namespace: podd
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 31800
  selector:
    app: front-end
  type: NodePort
status:
  loadBalancer: {}
