apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-web-app
    type: front-end-deploy
  name: my-web-app-canary-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: front-end
  type: ClusterIP
status:
  loadBalancer: {}
