apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-web-app
  name: my-web-appa-1
  namespace: podd
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 31496
  selector:
    app: my-web-app
  type: NodePort
status:
  loadBalancer: {}
