apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ingress-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/status
  - services
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - delete
