apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pgsql-deploy
  name: pgsql-service
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
    nodePort: 30808
  selector:
    app: pgsql-deploy
  type: NodePort
status:
  loadBalancer: {}
