apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: webapp
  name: mywebapp-np-svc
  namespace: ravi-prac
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31704
  selector:
    app: webapp
  type: NodePort
status:
  loadBalancer: {}
