apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: webapp
  name: mywebapp-tp-svc
  namespace: ravi-prac
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 80
  selector:
    app: webapp
status:
  loadBalancer: {}
