apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sunny
  name: sunny
  namespace: ravi-prac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sunny
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sunny
    spec:
      containers:
      - image: nginx:1.17.3-alpine
        name: nginx
        resources: {}
status: {}
