apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sunny
  name: sun-srv
  namespace: ravi-prac
spec:
  ports:
  - port: 9999
    protocol: TCP
    targetPort: 80
  selector:
    app: sunny
status:
  loadBalancer: {}
