apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: webapp
  name: mywebapp
  namespace: ravi-prac
spec:
  volumes:
  - name: webapp-volume
    emptyDir: {}
  containers:
  - image: nginx:1.17.3-alpine
    name: mywebapp
    ports:
      - containerPort: 80
    resources: {}
    volumeMounts:
      - name: webapp-volume
        mountPath: /cache
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
