apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mysql-sf-hl-svc
  name: mysql-sf-hl-svc
spec:
  clusterIP: None
  ports:
  - name: mysql-port
    port: 3306
  selector:
    app: mysql-sf-deploy
status:
  loadBalancer: {}
