apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysql-pod
  name: mysql-pod
spec:
  containers:
  - image: mysql/mysql-server
    name: mysql-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
