apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-0
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data0"
