apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    volume: persistent
  name: pv-sf
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  capacity:
    storage: 200Mi
  hostPath:
    path: /tmp
