apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: ingress-controller-svc
  namespace: ravi-ingress
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31080
  selector:
    name: nginx-ingress
  type: NodePort
status:
  loadBalancer: {}
