apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: ravi-ingress-rolebindings
  namespace: ravi-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ravi-ingress-role
subjects:
- kind: ServiceAccount
  name: ingress-serviceaccount
  namespace: ravi-ingress
