apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    type: loadbalaced
  name: nginx-pod
spec:
  containers:
  - image: nginx
    name: nginx-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
