apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    type: loadbalaced
  name: nginx-pod-lb-svc
spec:
  externalIPs:
    - "192.168.56.102"
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    type: loadbalaced
  type: LoadBalancer
status:
  loadBalancer: {}
