apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: f7d832feab9a44daff3835bb0c0b7343c13842b80ecdf91f769d2b3c4c89cb84
    cni.projectcalico.org/podIP: 192.168.59.78/32
    cni.projectcalico.org/podIPs: 192.168.59.78/32
  creationTimestamp: "2022-09-29T05:34:52Z"
  labels:
    run: liveness-exec
  name: liveness-exec
  namespace: default
  resourceVersion: "129363"
  uid: 97d71d1c-e5d3-4ccb-a6f9-c51d2a0fd7b7
spec:
  containers:
  - image: busybox
    command: ['sh', '-c']
    args:
     - |
       touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy
    imagePullPolicy: Always
    name: liveness-exec
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-p8572
      readOnly: true
    livenessProbe:
      exec:
       command: 
       - |
         cat /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: centos8-slave
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-p8572
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-09-29T05:34:55Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-09-29T05:34:55Z"
    message: 'containers with unready status: [liveness-exec]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-09-29T05:34:55Z"
    message: 'containers with unready status: [liveness-exec]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-09-29T05:34:52Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://9c2c7dd02e9d1e3fa8213a72524ca3972e2775aa1d54c8f06c30581c5f54492e
    image: docker.io/library/busybox:latest
    imageID: docker.io/library/busybox@sha256:ad9bd57a3a57cc95515c537b89aaa69d83a6df54c4050fcf2b41ad367bec0cd5
    lastState:
      terminated:
        containerID: containerd://9c2c7dd02e9d1e3fa8213a72524ca3972e2775aa1d54c8f06c30581c5f54492e
        exitCode: 128
        finishedAt: "2022-09-29T05:35:03Z"
        message: 'failed to create containerd task: OCI runtime create failed: container_linux.go:349:
          starting container process caused "exec: \"sh -c\": executable file not
          found in $PATH": unknown'
        reason: StartError
        startedAt: "1970-01-01T00:00:00Z"
    name: liveness-exec
    ready: false
    restartCount: 1
    started: false
    state:
      waiting:
        message: back-off 10s restarting failed container=liveness-exec pod=liveness-exec_default(97d71d1c-e5d3-4ccb-a6f9-c51d2a0fd7b7)
        reason: CrashLoopBackOff
  hostIP: 192.168.56.102
  phase: Running
  podIP: 192.168.59.78
  podIPs:
  - ip: 192.168.59.78
  qosClass: BestEffort
  startTime: "2022-09-29T05:34:55Z"
