apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: live-busybox
  name: live-busybox
  namespace: earth
spec:
  containers:
  - image: registry.k8s.io/busybox
    name: live-busybox
    command: ['/bin/sh', '-c']
    args:
    - |
      touch /tmp/healthy
      sleep 30
      rm -f /tmp/healthy
      sleep 600
    livenessProbe: 
      initialDelaySeconds: 5
      periodSeconds: 5
      exec:
        command:
        - cat
        - /tmp/healthy
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
