apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: first-pvc
  labels:
        sotrage: pvc-storage
spec:
  accessModes:
  - ReadWriteMany

  resources:
     requests:
       storage: 100Mi

  storageClassName: manual
