apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          #Adapt the tag 3.2-alpine as per image tag of redis you have downloaded.
          image: redis:3.2-alpine
          imagePullPolicy: IfNotPresent
          args: ["--appendonly", "yes", "--save", "900", "1", "--save", "30", "2"]
          ports:
            - containerPort: 6379
              name: redis
          securityContext:
            privileged: true
