apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 549b4edd933086f9ab024c5ab13026e7a4443a2f229f1dd8297a98b0f7e61c4d
    cni.projectcalico.org/podIP: 192.168.164.147/32
    cni.projectcalico.org/podIPs: 192.168.164.147/32
  creationTimestamp: "2023-06-14T05:47:09Z"
  generateName: redis-
  labels:
    app: redis
    controller-revision-hash: redis-698b9689d
    statefulset.kubernetes.io/pod-name: redis-0
  name: redis-0
  namespace: ravi-prac
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: redis
    uid: 81438403-bc47-4ed2-bb29-81da6948cee1
  resourceVersion: "1865838"
  uid: 30cd3649-8f4e-404a-bc21-4f9ddcb2ab18
spec:
  containers:
  - args:
    - --appendonly
    - "yes"
    - --save
    - "900"
    - "1"
    - --save
    - "30"
    - "2"
    image: redis:3.2-alpine
    imagePullPolicy: IfNotPresent
    name: redis
    ports:
    - containerPort: 6379
      name: redis
      protocol: TCP
    resources: {}
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-vdn6h
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: redis-0
  nodeName: centos-8-slave
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  subdomain: redis
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-vdn6h
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-06-14T05:47:09Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-06-14T05:47:17Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-06-14T05:47:17Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-06-14T05:47:09Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://f51a981b3cba1e6c0c568b49c3892112a882f1a5f0be197cffa52e2352661e37
    image: docker.io/library/redis:3.2-alpine
    imageID: docker.io/library/redis@sha256:e9083e10f5f81d350a3f687d582aefd06e114890b03e7f08a447fa1a1f66d967
    lastState: {}
    name: redis
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-06-14T05:47:17Z"
  hostIP: 192.168.136.129
  phase: Running
  podIP: 192.168.164.147
  podIPs:
  - ip: 192.168.164.147
  qosClass: BestEffort
  startTime: "2023-06-14T05:47:09Z"
