apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-webserver
  name: test-webserver
  namespace: ravi-prac
spec:
  containers:
  - image: registry.k8s.io/test-webserver
    name: test-webserver
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /tmp/hostPathVolume
      # this field is optional
      type: DirectoryOrCreate
status: {}
