apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: test-webserver
  name: test-webserver-svc
  namespace: ravi-prac
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    run: test-webserver
status:
  loadBalancer: {}
