apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: host-mount
  name: host-mount
  namespace: ravi-prac
spec:
  containers:
  - image: nginx:alpine
    name: host-mount
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /tmp/hostPathVolume
      # this field is optional
      type: DirectoryOrCreate
status: {}
