apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gui-app
    type: front-end
  name: nginx-svc
  namespace: podd
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: front-end
  type: ClusterIP
status:
  loadBalancer: {}
