apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: v1
  name: ngnix2
  namespace: podd
spec:
  containers:
  - image: nginx:alpine
    name: ngnix2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
