apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: v1
  name: ngnix3
  namespace: podd
spec:
  containers:
  - image: nginx:alpine
    name: ngnix3
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  nodeSelector:
    disk: ssd
status: {}
