apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: fronted
  name: podwithnodeselector
  namespace: podd
spec:
  containers:
  - image: nginx:alpine
    name: podwithnodeselector
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  nodeSelector:
    disk: ssd
status: {}
