apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: front-end
spec:
 replicas: 1
 selector:
  matchLabels:
    app: blue-pod
 strategy:
  rollingUpdate:
    maxSurge: 80%
    maxUnavailable: 20%
 template:
  metadata:
    name: busybpx-pod
    labels:
      app: blue-pod
  spec:
    containers:
    - name: busybpx-pod
      image: nginx
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c"]
      args:
      - |
        echo "I am here to test the for loop"
        sleep 30
        for i in {1..10}
        do
          echo "Testing $i : $(date)" >> /tmp/blue-pod-container.log
          sleep 5
        done


