apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: myapp
  name: myapp-container
  namespace: ravi-prac
spec:
  containers:
  - image: busybox:1.28
    name: myapp-container
    command: ['/bin/sh', '-c']
    args:
      - |
        echo "The app is running! && sleep 3600"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  initContainers:
  - image: busybox:1.28
    name: init-myservice
    command: ['/bin/sh', '-c']
    args:
      - |
        until nslookup myservice.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local
        do 
          echo "waiting for service to come up"
        done 
  - image: busybox:1.28
    name: init-mydb
    command: ['/bin/sh', '-c']
    args:
      - |
        until nslookup mydb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local
        do 
          echo "waiting for mydb to come up"
        done
status: {}
