apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mydb
  name: mydb
  namespace: ravi-prac
spec:
  ports:
  - name: 80-9377
    port: 80
    protocol: TCP
    targetPort: 9377
  selector:
    app: mydb
  type: ClusterIP
status:
  loadBalancer: {}
