apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myapp
    type: front-end
  name: bg-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    version: v2
  type: ClusterIP
status:
  loadBalancer: {}
