apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bg-version-1
  name: bg-version-svc
  namespace: ravi-prac
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
  selector:
    version: v2
  type: NodePort
status:
  loadBalancer: {}
