apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myapp
    type: front-end
  name: front-end-green-deploy
  namespace: ravi-prac
spec:
  replicas: 3
  selector:
    matchLabels:
      version: v2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      name: myapp-pod
      labels:
         version: v2
    spec:
      containers:
      - image: gcr.io/google-samples/hello-app:2.0
        name: hello-app-container
        resources: {}
status: {}
