apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: psql-deploy
  name: psql-svc
  namespace: ravi-prac
spec:
  ports:
  - port: 9898
    protocol: TCP
    targetPort: 5432
    nodePort: 31438
  selector:
    app: psql-deploy
  type: NodePort
status:
  loadBalancer: {}
