apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-pod
  name: nginx-pod
spec:
  serviceAccountName: cicd-sa
  automountServiceAccountToken: true
  containers:
  - image: nginx
    name: nginx-pod
    command: ["sleep", "1000"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
