apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: postgres
    env: prod
  name: postgres-pod
spec:
  containers:
  - env:
    - name: POSTGRES_DB
      value: postgresdb
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_PASSWORD
      value: postgres
    image: postgres
    name: postgres-pod
    ports:
    - containerPort: 5432
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
