apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: sa-pgsql-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sa-pgsql-role
subjects:
- kind: ServiceAccount
  name: pgsql-sa
  namespace: default
