apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: apache-https
  name: apache-https
spec:
  containers:
  - env:
    - name: HTTP_PORT
      value: "80"
    - name: HTTPS_PORT
      value: "443"
    image: httpd:1.0
    name: apache-https
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
