apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
  namespace: mynamespace
spec:
  containers:
  - image: busybox
    name: busybox
    command: ['env']
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
