apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dep-strategy
  name: dep-strategy
  namespace: earth
spec:
  replicas: 4
  selector:
    matchLabels:
      app: dep-strategy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dep-strategy
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
        resources: {}
status: {}
