apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: webserver
    env: production
  name: kplabs-label
spec:
  containers:
  - image: nginx
    name: nginx-container
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
