apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kplabs-cmdargs
  name: kplabs-cmdargs
  namespace: ravi-prac
spec:
  containers:
  - image: nginx
    name: kplabs-cmdargs
    command: ['/bin/sh', '-c']
    args:
      - |
        i=0;
        while true;
        do
        echo "$i: $(date)" >> /var/log/1.log;
        echo "$(date) INFO $i" >> /var/log/2.log;
        i=$((i+1));
        sleep 1;
        done
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
