apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kplabs-nginx
  name: kplabs-nginx
  namespace: ravi-prac
spec:
  containers:
  - image: mykplabs/kubernetes:nginx
    name: mycontainer
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
