apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: kplabs-cronjob
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: kplabs-cronjob
    spec:
      activeDeadlineSeconds: 10
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - curl kplabs.in/ping
            image: httpd
            name: kplabs-cronjob
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}
