apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kplabs-deployment
  name: kplabs-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy: 
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 30
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
      nodeSelector:
        disk: ssd
status: {}
