apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: nginx-pod
  name: nginx-pod-svc
spec:
  ports:
  - port: 9999
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx-pod
  type: ClusterIP
status:
  loadBalancer: {}
