apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: resource-checker
  name: resource-checker
spec:
  containers:
  - image: httpd:alpine
    name: resource-checker
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
