apiVersion: v1
kind: Pod
metadata:
  name: busy-box-pod
  labels:
    name: busy-box-pod
    app:  backend-app

spec:
  initContainers:
    - name: check-voting-app
      image: busybox:1.28
      #command: ['sh', '-c']
      command:
        - |
          sh
          -c
      args:
        - |

          for i in {1..5}
          do sleep 2
          if [ `curl -s -o /dev/null -w "%{http_code}" http://centos8-Slave:32020` =  200 ]
          then 
            echo "voting-service up" > /tmp/checksvc.log
          else
            echo "voting-service not up"
          fi
          done

  containers:
    - name: busy-box
      image: busybox:1.28
