apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    my-laebl: test
  name: testpod
  namespace: ravi-prac
spec:
  containers:
  - image: bash
    name: testpod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
