apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test
  name: test
spec:
  containers:
  - image: busybox
    name: test
    ports:
    - containerPort: 6754
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
